install:
  # Redis
  - choco install redis-64
  - redis-server --service-install
  - redis-server --service-start

  # Node
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version
  - npm --version

  - npm install || npm install

test_script:
  - npm test

environment:
  matrix:
    - nodejs_version: 6

init:
  - git config --global core.autocrlf false

build: off
deploy: off
